TRUNCATE TABLE productos;
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Carrara Dream PL 60x60.png', 'productos/BRASIL/Carrara Dream PL 60x60.png', 'BRASIL', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('shine plus.png', 'productos/BRASIL/shine plus.png', 'BRASIL', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('simona almond.png', 'productos/BRASIL/simona almond.png', 'BRASIL', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('simona white.png', 'productos/BRASIL/simona white.png', 'BRASIL', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('simona_grey.png', 'productos/BRASIL/simona_grey.png', 'BRASIL', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('tivoli gray.png', 'productos/BRASIL/tivoli gray.png', 'BRASIL', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('tivoli nude.png', 'productos/BRASIL/tivoli nude.png', 'BRASIL', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('basalto beige.png', 'productos/BRASIL/56X113/basalto beige.png', 'BRASIL', '56X113');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('carrara gold.png', 'productos/BRASIL/56X113/carrara gold.png', 'BRASIL', '56X113');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('carrara-gold-f5-105f6e1447-800_x_800.png', 'productos/BRASIL/56X113/carrara-gold-f5-105f6e1447-800_x_800.png', 'BRASIL', '56X113');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('carrara-gold-f6-620d188a3c-800_x_800.png', 'productos/BRASIL/56X113/carrara-gold-f6-620d188a3c-800_x_800.png', 'BRASIL', '56X113');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('carrara-gold-f7-b9387e3d57-800_x_800.png', 'productos/BRASIL/56X113/carrara-gold-f7-b9387e3d57-800_x_800.png', 'BRASIL', '56X113');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('concretisimo 2.png', 'productos/BRASIL/56X113/concretisimo 2.png', 'BRASIL', '56X113');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('concretisimo-savane.png', 'productos/BRASIL/56X113/concretisimo-savane.png', 'BRASIL', '56X113');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('corten.png', 'productos/BRASIL/56X113/corten.png', 'BRASIL', '56X113');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('legno marrone.png', 'productos/BRASIL/56X113/legno marrone.png', 'BRASIL', '56X113');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('bromo.png', 'productos/BRASIL/gres/bromo.png', 'BRASIL', 'gres');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('coimbra.png', 'productos/BRASIL/gres/coimbra.png', 'BRASIL', 'gres');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('misisipi.png', 'productos/BRASIL/gres/misisipi.png', 'BRASIL', 'gres');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('nilo.png', 'productos/BRASIL/gres/nilo.png', 'BRASIL', 'gres');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('palazzo.png', 'productos/BRASIL/gres/palazzo.png', 'BRASIL', 'gres');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('villarica.png', 'productos/BRASIL/gres/villarica.png', 'BRASIL', 'gres');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('sand beige.png', 'productos/BRASIL/nuevo savane/sand beige.png', 'BRASIL', 'nuevo savane');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('sand gray.png', 'productos/BRASIL/nuevo savane/sand gray.png', 'BRASIL', 'nuevo savane');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('terrazine bianco.png', 'productos/BRASIL/nuevo savane/terrazine bianco.png', 'BRASIL', 'nuevo savane');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('terrazine.png', 'productos/BRASIL/nuevo savane/terrazine.png', 'BRASIL', 'nuevo savane');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('venato-120-mate-1.png', 'productos/BRASIL/nuevo savane/venato-120-mate-1.png', 'BRASIL', 'nuevo savane');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('boss white.png', 'productos/BRASIL/revestimiento/boss white.png', 'BRASIL', 'revestimiento');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('CAPRI IVORY NEW.png', 'productos/BRASIL/revestimiento/CAPRI IVORY NEW.png', 'BRASIL', 'revestimiento');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('magno cm - copia.png', 'productos/BRASIL/revestimiento/magno cm - copia.png', 'BRASIL', 'revestimiento');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('marino black - copia - copia.png', 'productos/BRASIL/revestimiento/marino black - copia - copia.png', 'BRASIL', 'revestimiento');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('marino white.png', 'productos/BRASIL/revestimiento/marino white.png', 'BRASIL', 'revestimiento');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('ripiado blanco - copia.png', 'productos/BRASIL/revestimiento/ripiado blanco - copia.png', 'BRASIL', 'revestimiento');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('ripiado horz.png', 'productos/BRASIL/revestimiento/ripiado horz.png', 'BRASIL', 'revestimiento');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('carrara dream 60x60.png', 'productos/BRASIL/satinado/carrara dream 60x60.png', 'BRASIL', 'satinado');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('images.png', 'productos/BRASIL/satinado/images.png', 'BRASIL', 'satinado');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('noir ac.png', 'productos/BRASIL/satinado/noir ac.png', 'BRASIL', 'satinado');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('quebe ice AC 61x61.png', 'productos/BRASIL/satinado/quebe ice AC 61x61.png', 'BRASIL', 'satinado');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('quebec ice.png', 'productos/BRASIL/satinado/quebec ice.png', 'BRASIL', 'satinado');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('soho cement.png', 'productos/BRASIL/satinado/soho cement.png', 'BRASIL', 'satinado');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('urban beige 2.png', 'productos/BRASIL/satinado/urban beige 2.png', 'BRASIL', 'satinado');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('urban grigio.png', 'productos/BRASIL/satinado/urban grigio.png', 'BRASIL', 'satinado');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('urban whit2e.png', 'productos/BRASIL/satinado/urban whit2e.png', 'BRASIL', 'satinado');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('amazon brown.png', 'productos/BRASIL/TABLONES/amazon brown.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('amazonas camel.png', 'productos/BRASIL/TABLONES/amazonas camel.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('amazonas taupe.png', 'productos/BRASIL/TABLONES/amazonas taupe.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Amazonas tavola belige.png', 'productos/BRASIL/TABLONES/Amazonas tavola belige.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('amazonas white.png', 'productos/BRASIL/TABLONES/amazonas white.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('legno noce.png', 'productos/BRASIL/TABLONES/legno noce.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('madero.png', 'productos/BRASIL/TABLONES/madero.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('malbec rt.png', 'productos/BRASIL/TABLONES/malbec rt.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('merlot compuesto.png', 'productos/BRASIL/TABLONES/merlot compuesto.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('merlot.png', 'productos/BRASIL/TABLONES/merlot.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('natural beige.png', 'productos/BRASIL/TABLONES/natural beige.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('natural gray.png', 'productos/BRASIL/TABLONES/natural gray.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('norway nordic.png', 'productos/BRASIL/TABLONES/norway nordic.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PAVIA GRIGIO 3.png', 'productos/BRASIL/TABLONES/PAVIA GRIGIO 3.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('pavia marrone COMPUESTO.png', 'productos/BRASIL/TABLONES/pavia marrone COMPUESTO.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('pavia marrone.png', 'productos/BRASIL/TABLONES/pavia marrone.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('pavia-grigio-1.png', 'productos/BRASIL/TABLONES/pavia-grigio-1.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('tavola beige - copia.png', 'productos/BRASIL/TABLONES/tavola beige - copia.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('tavola beige.png', 'productos/BRASIL/TABLONES/tavola beige.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('tenese amber.png', 'productos/BRASIL/TABLONES/tenese amber.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('tenesse compuesto.png', 'productos/BRASIL/TABLONES/tenesse compuesto.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('vetus 15X90.png', 'productos/BRASIL/TABLONES/vetus 15X90.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('walnut golden.png', 'productos/BRASIL/TABLONES/walnut golden.png', 'BRASIL', 'TABLONES');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('d603.png', 'productos/CHINOS/AGOTADOS/d603.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('D605.png', 'productos/CHINOS/AGOTADOS/D605.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('D618.png', 'productos/CHINOS/AGOTADOS/D618.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('G126G1103.png', 'productos/CHINOS/AGOTADOS/G126G1103.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('HP6718.png', 'productos/CHINOS/AGOTADOS/HP6718.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('J6500G.png', 'productos/CHINOS/AGOTADOS/J6500G.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('J6J12.png', 'productos/CHINOS/AGOTADOS/J6J12.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JCM6108H.png', 'productos/CHINOS/AGOTADOS/JCM6108H.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JCM6B008.png', 'productos/CHINOS/AGOTADOS/JCM6B008.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JM63573D.png', 'productos/CHINOS/AGOTADOS/JM63573D.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JM63804.png', 'productos/CHINOS/AGOTADOS/JM63804.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PC002.png', 'productos/CHINOS/AGOTADOS/PC002.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('SM6053.png', 'productos/CHINOS/AGOTADOS/SM6053.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('SS.png', 'productos/CHINOS/AGOTADOS/SS.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('SSA03- PORCELANATO.png', 'productos/CHINOS/AGOTADOS/SSA03- PORCELANATO.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('SSA17.png', 'productos/CHINOS/AGOTADOS/SSA17.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WhatsApp Image 2023-12-13 at 09.19.14.png', 'productos/CHINOS/AGOTADOS/WhatsApp Image 2023-12-13 at 09.19.14.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('ym6601.png', 'productos/CHINOS/AGOTADOS/ym6601.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('YM6612.png', 'productos/CHINOS/AGOTADOS/YM6612.png', 'CHINOS', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('MINERAL.png', 'productos/CHINOS/FBA/MINERAL.png', 'CHINOS', 'FBA');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('OCEAN AQUA.png', 'productos/CHINOS/FBA/OCEAN AQUA.png', 'CHINOS', 'FBA');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('OCEAN BLUE.png', 'productos/CHINOS/FBA/OCEAN BLUE.png', 'CHINOS', 'FBA');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('OCEAN GOLD.png', 'productos/CHINOS/FBA/OCEAN GOLD.png', 'CHINOS', 'FBA');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('6684.jpg', 'productos/CHINOS/INDIGO/6684.jpg', 'CHINOS', 'INDIGO');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('FG6602.jpg', 'productos/CHINOS/INDIGO/FG6602.jpg', 'CHINOS', 'INDIGO');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('FG6603.jpg', 'productos/CHINOS/INDIGO/FG6603.jpg', 'CHINOS', 'INDIGO');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('FG6604.png', 'productos/CHINOS/INDIGO/FG6604.png', 'CHINOS', 'INDIGO');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('FG6605.jpg', 'productos/CHINOS/INDIGO/FG6605.jpg', 'CHINOS', 'INDIGO');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('marea-blue.png', 'productos/CHINOS/INDIGO/marea-blue.png', 'CHINOS', 'INDIGO');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('marea-mint-1.png', 'productos/CHINOS/INDIGO/marea-mint-1.png', 'CHINOS', 'INDIGO');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('marea-silver-1.png', 'productos/CHINOS/INDIGO/marea-silver-1.png', 'CHINOS', 'INDIGO');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('marea-silver.png', 'productos/CHINOS/INDIGO/marea-silver.png', 'CHINOS', 'INDIGO');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PD6683.jpg', 'productos/CHINOS/INDIGO/PD6683.jpg', 'CHINOS', 'INDIGO');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PD6691.jpg', 'productos/CHINOS/INDIGO/PD6691.jpg', 'CHINOS', 'INDIGO');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('terra1.png', 'productos/CHINOS/INDIGO/terra1.png', 'CHINOS', 'INDIGO');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de G126G1102.png', 'productos/CHINOS/JBN/60X120/Copia de G126G1102.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de JM.png', 'productos/CHINOS/JBN/60X120/Copia de JM.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de jm126613-2(1).jpg', 'productos/CHINOS/JBN/60X120/Copia de jm126613-2(1).jpg', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de jm126613-2.jpg', 'productos/CHINOS/JBN/60X120/Copia de jm126613-2.jpg', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de JM126613.jpg', 'productos/CHINOS/JBN/60X120/Copia de JM126613.jpg', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de JM126614.png', 'productos/CHINOS/JBN/60X120/Copia de JM126614.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JM126614.jpg', 'productos/CHINOS/JBN/60X120/JM126614.jpg', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JM126615.jpg', 'productos/CHINOS/JBN/60X120/JM126615.jpg', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('terrazno light.png', 'productos/CHINOS/JBN/60X120/terrazno light.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('terrazo grigio.png', 'productos/CHINOS/JBN/60X120/terrazo grigio.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('armani gris.png', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/armani gris.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('blue boreal.png', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/blue boreal.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('castello gris.png', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/castello gris.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de baltic.png', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/Copia de baltic.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de Copia de Copia de D611.PNG', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/Copia de Copia de Copia de D611.PNG', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de Copia de JM6615.PNG', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/Copia de Copia de JM6615.PNG', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de VIENA BLANCO.png', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/Copia de VIENA BLANCO.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('duna gris.png', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/duna gris.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('glacial.png', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/glacial.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('imperial bronce.png', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/imperial bronce.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JBM6148D-FONTANA BLUE.png', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/JBM6148D-FONTANA BLUE.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JBM6199D- COSMIC GREY.png', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/JBM6199D- COSMIC GREY.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JBM6215DC- VIA LACTEA.png', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/JBM6215DC- VIA LACTEA.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JM64148D-calacatta aura.png', 'productos/CHINOS/JBN/60X60 LINEA D NUEVOS/JM64148D-calacatta aura.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JM63387.png', 'productos/CHINOS/JBN/MASA NEGRA DF/JM63387.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JM63805D.png', 'productos/CHINOS/JBN/MASA NEGRA DF/JM63805D.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JM63975D.png', 'productos/CHINOS/JBN/MASA NEGRA DF/JM63975D.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JM6608.jpg', 'productos/CHINOS/JBN/MASA NEGRA DF/JM6608.jpg', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de J6T00.PNG', 'productos/CHINOS/JBN/PULIDOS/Copia de J6T00.PNG', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de jS6800.PNG', 'productos/CHINOS/JBN/PULIDOS/Copia de jS6800.PNG', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de JS6835 A30.jpg', 'productos/CHINOS/JBN/PULIDOS/Copia de JS6835 A30.jpg', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de JS6861.png', 'productos/CHINOS/JBN/PULIDOS/Copia de JS6861.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Copia de luni.png', 'productos/CHINOS/JBN/PULIDOS/Copia de luni.png', 'CHINOS', 'JBN');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('21D 2.png', 'productos/CHINOS/nuevos/21D 2.png', 'CHINOS', 'nuevos');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('23D 1.png', 'productos/CHINOS/nuevos/23D 1.png', 'CHINOS', 'nuevos');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('LUNI.png', 'productos/CHINOS/nuevos/LUNI.png', 'CHINOS', 'nuevos');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Marea Blue.png', 'productos/CHINOS/nuevos dic/Marea Blue.png', 'CHINOS', 'nuevos dic');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Marea Silver.png', 'productos/CHINOS/nuevos dic/Marea Silver.png', 'CHINOS', 'nuevos dic');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Marea Terra.png', 'productos/CHINOS/nuevos dic/Marea Terra.png', 'CHINOS', 'nuevos dic');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('MAREA-MINT.png', 'productos/CHINOS/nuevos dic/MAREA-MINT.png', 'CHINOS', 'nuevos dic');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('61837 -marmo graffito.png', 'productos/CHINOS/NUEVOS OCT/61837 -marmo graffito.png', 'CHINOS', 'NUEVOS OCT');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('ATLANTIC - PD6692.png', 'productos/CHINOS/NUEVOS OCT/ATLANTIC - PD6692.png', 'CHINOS', 'NUEVOS OCT');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('carrara bianco.png', 'productos/CHINOS/NUEVOS OCT/carrara bianco.png', 'CHINOS', 'NUEVOS OCT');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('dallas gris-SHH60025.png', 'productos/CHINOS/NUEVOS OCT/dallas gris-SHH60025.png', 'CHINOS', 'NUEVOS OCT');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('lux gold-SHH60014.png', 'productos/CHINOS/NUEVOS OCT/lux gold-SHH60014.png', 'CHINOS', 'NUEVOS OCT');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('10D.png', 'productos/CHINOS/SERIE DS/10D.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('11D.png', 'productos/CHINOS/SERIE DS/11D.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('12D.png', 'productos/CHINOS/SERIE DS/12D.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('15D.png', 'productos/CHINOS/SERIE DS/15D.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('16D.png', 'productos/CHINOS/SERIE DS/16D.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('19D.png', 'productos/CHINOS/SERIE DS/19D.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('19D2.png', 'productos/CHINOS/SERIE DS/19D2.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JCM61010D.png', 'productos/CHINOS/SERIE DS/JCM61010D.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JCM61012D.png', 'productos/CHINOS/SERIE DS/JCM61012D.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JCM61024D.png', 'productos/CHINOS/SERIE DS/JCM61024D.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('jcm6110d.png', 'productos/CHINOS/SERIE DS/jcm6110d.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JCM614113D 8.png', 'productos/CHINOS/SERIE DS/JCM614113D 8.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JCM61417D-8.png', 'productos/CHINOS/SERIE DS/JCM61417D-8.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JCM61418D 8.png', 'productos/CHINOS/SERIE DS/JCM61418D 8.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JCM61421D-8.png', 'productos/CHINOS/SERIE DS/JCM61421D-8.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JCM61422D 8.png', 'productos/CHINOS/SERIE DS/JCM61422D 8.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('JCM61424D.png', 'productos/CHINOS/SERIE DS/JCM61424D.png', 'CHINOS', 'SERIE DS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2031.png', 'productos/HINDU/2031.png', 'HINDU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2092.png', 'productos/HINDU/2092.png', 'HINDU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2214.png', 'productos/HINDU/2214.png', 'HINDU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2277.png', 'productos/HINDU/2277.png', 'HINDU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('crystal almond.png', 'productos/HINDU/crystal almond.png', 'HINDU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Crystal Grey 60x60.png', 'productos/HINDU/Crystal Grey 60x60.png', 'HINDU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('satvario fora.png', 'productos/HINDU/satvario fora.png', 'HINDU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Alyssa Reen 60x120.png', 'productos/HINDU/60X120/Alyssa Reen 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('ANTIQUE WOOD.png', 'productos/HINDU/60X120/ANTIQUE WOOD.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Ardesia Blue.png', 'productos/HINDU/60X120/Ardesia Blue.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Arico Green 60x120.png', 'productos/HINDU/60X120/Arico Green 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Barizo Blue 60x120 - copia.png', 'productos/HINDU/60X120/Barizo Blue 60x120 - copia.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('black volcan.png', 'productos/HINDU/60X120/black volcan.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Calcutta Elite 60x120 - copia.png', 'productos/HINDU/60X120/Calcutta Elite 60x120 - copia.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('CLASSICAL WOOD.png', 'productos/HINDU/60X120/CLASSICAL WOOD.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Crystal Grey 60x120.png', 'productos/HINDU/60X120/Crystal Grey 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('dahino azul.png', 'productos/HINDU/60X120/dahino azul.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Elmwood Brown.png', 'productos/HINDU/60X120/Elmwood Brown.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Essen Brown.png', 'productos/HINDU/60X120/Essen Brown.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Fentastico Onyx 60x120.png', 'productos/HINDU/60X120/Fentastico Onyx 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Flourish Ice 60x120.png', 'productos/HINDU/60X120/Flourish Ice 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('gray onyx.png', 'productos/HINDU/60X120/gray onyx.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Newtro Blue 60x120.png', 'productos/HINDU/60X120/Newtro Blue 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Newtro Brown 60x120.png', 'productos/HINDU/60X120/Newtro Brown 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Olmo Blue 60x120.png', 'productos/HINDU/60X120/Olmo Blue 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Olmo Nero 60x120.png', 'productos/HINDU/60X120/Olmo Nero 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('River Rock Gris 60x120.png', 'productos/HINDU/60X120/River Rock Gris 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('scott blue.png', 'productos/HINDU/60X120/scott blue.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Scott Green 60x120.png', 'productos/HINDU/60X120/Scott Green 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Scottish Green 60x120.png', 'productos/HINDU/60X120/Scottish Green 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Stallone Marble 60x120.png', 'productos/HINDU/60X120/Stallone Marble 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Super Black 60x120.png', 'productos/HINDU/60X120/Super Black 60x120.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Touchwood Cherry.png', 'productos/HINDU/60X120/Touchwood Cherry.png', 'HINDU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2006.png', 'productos/HINDU/AGOTADOS/2006.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2018 60x60 .png', 'productos/HINDU/AGOTADOS/2018 60x60 .png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2022 60x60.png', 'productos/HINDU/AGOTADOS/2022 60x60.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2026.png', 'productos/HINDU/AGOTADOS/2026.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2027 60x60.png', 'productos/HINDU/AGOTADOS/2027 60x60.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2048 60x60.png', 'productos/HINDU/AGOTADOS/2048 60x60.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2077 60x60.png', 'productos/HINDU/AGOTADOS/2077 60x60.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2078 60x60.png', 'productos/HINDU/AGOTADOS/2078 60x60.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2091.png', 'productos/HINDU/AGOTADOS/2091.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2092.png', 'productos/HINDU/AGOTADOS/2092.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2113 60x60.png', 'productos/HINDU/AGOTADOS/2113 60x60.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2125 60x60.png', 'productos/HINDU/AGOTADOS/2125 60x60.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2215.png', 'productos/HINDU/AGOTADOS/2215.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2217 60x60 Ambiente.png', 'productos/HINDU/AGOTADOS/2217 60x60 Ambiente.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2217.png', 'productos/HINDU/AGOTADOS/2217.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2247.png', 'productos/HINDU/AGOTADOS/2247.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('2262.png', 'productos/HINDU/AGOTADOS/2262.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('8012.png', 'productos/HINDU/AGOTADOS/8012.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('8022.png', 'productos/HINDU/AGOTADOS/8022.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('8049.png', 'productos/HINDU/AGOTADOS/8049.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('8058.png', 'productos/HINDU/AGOTADOS/8058.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('8059.png', 'productos/HINDU/AGOTADOS/8059.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('8092.png', 'productos/HINDU/AGOTADOS/8092.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('calcutta 60x60.png', 'productos/HINDU/AGOTADOS/calcutta 60x60.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('cosmos blue.png', 'productos/HINDU/AGOTADOS/cosmos blue.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('houston-2.png', 'productos/HINDU/AGOTADOS/houston-2.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Jet Rock 60x60.png', 'productos/HINDU/AGOTADOS/Jet Rock 60x60.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Nolte Green 60x60.png', 'productos/HINDU/AGOTADOS/Nolte Green 60x60.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('onyx gray.png', 'productos/HINDU/AGOTADOS/onyx gray.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('satvario-spirit.png', 'productos/HINDU/AGOTADOS/satvario-spirit.png', 'HINDU', 'AGOTADOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('mineral teal.png', 'productos/HINDU/carving/mineral teal.png', 'HINDU', 'carving');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('navala.png', 'productos/HINDU/carving/navala.png', 'HINDU', 'carving');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PIENZA-GRIS.png', 'productos/HINDU/carving/PIENZA-GRIS.png', 'HINDU', 'carving');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('zinc-2.png', 'productos/HINDU/carving/zinc-2.png', 'HINDU', 'carving');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('crista-grey.png', 'productos/HINDU/HIGH GLOSS/crista-grey.png', 'HINDU', 'HIGH GLOSS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('lisa-satvario.png', 'productos/HINDU/HIGH GLOSS/lisa-satvario.png', 'HINDU', 'HIGH GLOSS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('marino-ivory-1.png', 'productos/HINDU/HIGH GLOSS/marino-ivory-1.png', 'HINDU', 'HIGH GLOSS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('MARTINO-SAGE1.png', 'productos/HINDU/HIGH GLOSS/MARTINO-SAGE1.png', 'HINDU', 'HIGH GLOSS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('travo.png', 'productos/HINDU/HIGH GLOSS/travo.png', 'HINDU', 'HIGH GLOSS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('vivian-grey.png', 'productos/HINDU/HIGH GLOSS/vivian-grey.png', 'HINDU', 'HIGH GLOSS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Alpine Wood 60x60.png', 'productos/HINDU/PULIDOS/Alpine Wood 60x60.png', 'HINDU', 'PULIDOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Ivory 60x60.png', 'productos/HINDU/PULIDOS/Ivory 60x60.png', 'HINDU', 'PULIDOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Natural Wood 60x60.png', 'productos/HINDU/PULIDOS/Natural Wood 60x60.png', 'HINDU', 'PULIDOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Solo Wood 60x60.png', 'productos/HINDU/PULIDOS/Solo Wood 60x60.png', 'HINDU', 'PULIDOS');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('3d-cubic.png', 'productos/PERU/3d-cubic.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('60602095.png', 'productos/PERU/60602095.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('AGATA.png', 'productos/PERU/AGATA.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('olimpo-gold.png', 'productos/PERU/olimpo-gold.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('pacific-gold.png', 'productos/PERU/pacific-gold.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('Persa-Gold.png', 'productos/PERU/Persa-Gold.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66010 -COMPLETO.png', 'productos/PERU/PPY66010 -COMPLETO.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('ppy66010.png', 'productos/PERU/ppy66010.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('ppy66012 - completo.jpg', 'productos/PERU/ppy66012 - completo.jpg', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('ppy66012 - completo.png', 'productos/PERU/ppy66012 - completo.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66012.png', 'productos/PERU/PPY66012.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66019.png', 'productos/PERU/PPY66019.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66023.png', 'productos/PERU/PPY66023.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66028.png', 'productos/PERU/PPY66028.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66031.png', 'productos/PERU/PPY66031.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66035.png', 'productos/PERU/PPY66035.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66036.png', 'productos/PERU/PPY66036.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66039.png', 'productos/PERU/PPY66039.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66040.png', 'productos/PERU/PPY66040.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66044.png', 'productos/PERU/PPY66044.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66046.png', 'productos/PERU/PPY66046.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('ppy66055.png', 'productos/PERU/ppy66055.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('ppy66059.png', 'productos/PERU/ppy66059.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY66069.png', 'productos/PERU/PPY66069.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PY003.png', 'productos/PERU/PY003.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PY66009-1.png', 'productos/PERU/PY66009-1.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('siberian.png', 'productos/PERU/siberian.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('tria-oro.png', 'productos/PERU/tria-oro.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('VULCANO.png', 'productos/PERU/VULCANO.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('w88.png', 'productos/PERU/w88.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66011.png', 'productos/PERU/WPY66011.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66013.png', 'productos/PERU/WPY66013.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66018.png', 'productos/PERU/WPY66018.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66027.png', 'productos/PERU/WPY66027.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66031 - OXFORD GREY.png', 'productos/PERU/WPY66031 - OXFORD GREY.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66034.png', 'productos/PERU/WPY66034.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66037.png', 'productos/PERU/WPY66037.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66057.png', 'productos/PERU/WPY66057.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66058.png', 'productos/PERU/WPY66058.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66062.PNG-VENATO GOLD.png', 'productos/PERU/WPY66062.PNG-VENATO GOLD.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66063.png', 'productos/PERU/WPY66063.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66100-TORNADO AQUA.png', 'productos/PERU/WPY66100-TORNADO AQUA.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY66103-IMPERIAL GREY GOLD.png', 'productos/PERU/WPY66103-IMPERIAL GREY GOLD.png', 'PERU', 'General');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('DLPY12017.png', 'productos/PERU/60X120/DLPY12017.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('DPPY12026.png', 'productos/PERU/60X120/DPPY12026.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('IMAGENES-DE-4.png', 'productos/PERU/60X120/IMAGENES-DE-4.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('LPY12019-2.png', 'productos/PERU/60X120/LPY12019-2.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('LPY12019-3.png', 'productos/PERU/60X120/LPY12019-3.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('LPY12019.png', 'productos/PERU/60X120/LPY12019.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('LPY12024.png', 'productos/PERU/60X120/LPY12024.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY12020-1.png', 'productos/PERU/60X120/PPY12020-1.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY12020-2.png', 'productos/PERU/60X120/PPY12020-2.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY12020-3.png', 'productos/PERU/60X120/PPY12020-3.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY12026-1.png', 'productos/PERU/60X120/PPY12026-1.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY12026-2.png', 'productos/PERU/60X120/PPY12026-2.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY12026-3.png', 'productos/PERU/60X120/PPY12026-3.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PPY12026-4.png', 'productos/PERU/60X120/PPY12026-4.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('wpy12001-2.png', 'productos/PERU/60X120/wpy12001-2.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('wpy12001-3.png', 'productos/PERU/60X120/wpy12001-3.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('wpy12001-4.png', 'productos/PERU/60X120/wpy12001-4.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('WPY12001.png', 'productos/PERU/60X120/WPY12001.png', 'PERU', '60X120');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('LSJ66098S.png', 'productos/PERU/CERAMICA/LSJ66098S.png', 'PERU', 'CERAMICA');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('LSJ66099S.png', 'productos/PERU/CERAMICA/LSJ66099S.png', 'PERU', 'CERAMICA');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('LSJ66100S.png', 'productos/PERU/CERAMICA/LSJ66100S.png', 'PERU', 'CERAMICA');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('80c.png', 'productos/PERU/REVEST/80c.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('LLG36001C.png', 'productos/PERU/REVEST/LLG36001C.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('llg36003.png', 'productos/PERU/REVEST/llg36003.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('LLG36003C.png', 'productos/PERU/REVEST/LLG36003C.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('LLG36008C.png', 'productos/PERU/REVEST/LLG36008C.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PLG36001.png', 'productos/PERU/REVEST/PLG36001.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PLG36002.png', 'productos/PERU/REVEST/PLG36002.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PLG36006A.png', 'productos/PERU/REVEST/PLG36006A.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PLG36006B.png', 'productos/PERU/REVEST/PLG36006B.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PLG36008A.png', 'productos/PERU/REVEST/PLG36008A.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PLG36008B.png', 'productos/PERU/REVEST/PLG36008B.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PLG36008C.png', 'productos/PERU/REVEST/PLG36008C.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('plg36010c.png', 'productos/PERU/REVEST/plg36010c.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PLG36020A.png', 'productos/PERU/REVEST/PLG36020A.png', 'PERU', 'REVEST');
INSERT INTO productos (nombre, ruta_imagen, procedencia, tipo) VALUES ('PLG36068C.png', 'productos/PERU/REVEST/PLG36068C.png', 'PERU', 'REVEST');

